// Generated by CoffeeScript 1.10.0
(function() {
  var bind,
    slice = [].slice;

  bind = function(functionObject) {
    var result;
    result = functionObject.bind.apply(functionObject, Array.prototype.slice.call(arguments, 1));
    result.bind = function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return Function.prototype.bind.apply(functionObject, args);
    };
    return result;
  };

  module.exports = bind;

}).call(this);

//# sourceMappingURL=bind.js.map
